/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as TeenRouteImport } from './routes/teen'
import { Route as CompanyRouteImport } from './routes/company'
import { Route as IndexRouteImport } from './routes/index'

const TeenRoute = TeenRouteImport.update({
  id: '/teen',
  path: '/teen',
  getParentRoute: () => rootRouteImport,
} as any)
const CompanyRoute = CompanyRouteImport.update({
  id: '/company',
  path: '/company',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/company': typeof CompanyRoute
  '/teen': typeof TeenRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/company': typeof CompanyRoute
  '/teen': typeof TeenRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/company': typeof CompanyRoute
  '/teen': typeof TeenRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/company' | '/teen'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/company' | '/teen'
  id: '__root__' | '/' | '/company' | '/teen'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  CompanyRoute: typeof CompanyRoute
  TeenRoute: typeof TeenRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/teen': {
      id: '/teen'
      path: '/teen'
      fullPath: '/teen'
      preLoaderRoute: typeof TeenRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/company': {
      id: '/company'
      path: '/company'
      fullPath: '/company'
      preLoaderRoute: typeof CompanyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  CompanyRoute: CompanyRoute,
  TeenRoute: TeenRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
